source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'ImageColors_Example' do
    
  pod 'ImageColors', :path => '../'
  pod 'AlamofireImage', '~> 1.0'
  pod 'Alamofire', '~> 3.0'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  
end

target 'ImageColors_Tests' do
    
  pod 'ImageColors', :path => '../'

end
