source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'ImageColors_Example' do
    
  pod 'ImageColors', :path => '../'
  pod 'AlamofireImage'
  pod 'Alamofire'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  
end

target 'ImageColors_Tests' do
    
  pod 'ImageColors', :path => '../'

end
